### ISSUE TITLE
As a user in a game, I want to collaborate with on other team member to play the game

### ISSUE THREAD

**Issue by ElenaGrafUZH** [sopra-fs22-group-29/brandi-server#123]
**Acceptance Criteria**

- exchange cards at beginning of each round with your partner
- see how your partner is

**Tasks**
- [x] sopra-fs22-group-29/brandi-server#124
- [x] sopra-fs22-group-29/brandi-client#76
- [ ] sopra-fs22-group-29/brandi-client#75
- [x] #155
