### ISSUE TITLE
As a registered user currently in a game session, I want to be able to leave the game even  when it is not done playing yet and re-enter it at another time such that if I don’t have enough  time, I can continue playing the game at some other time

### ISSUE THREAD

**Issue by EriCreator** [sopra-fs22-group-29/brandi-server#16]
**Acceptance Criteria:**

- Upon clicking a pause-button, the user gets asked if he's sure to pause the game. If he agrees, the user gets redirected to the game overview page. All other players get a notification that someone paused the game and they get redirected to the game overview page as well.
-  When a user gets disconnected: The status of the user is set to offline such that the other players know that the user left their game. On his turn after 5 minutes of being disconnected, the users team is disqualified and loses the game. 
- Users can re-enter the paused game. The game will resume when all players rejoined.
- Upon clicking an end-game-button, the user gets asked if he's sure to end the game. If the user agrees, the game ends and he gets redirected to the game overview page. All other player get a notification that someone ended the game and they get redirected to the game overview page as well.

**Tasks**
- [x] sopra-fs22-group-29/brandi-client#16

- [x] sopra-fs22-group-29/brandi-client#17

- [x] sopra-fs22-group-29/brandi-client#18

- [x] sopra-fs22-group-29/brandi-client#19

- [x] sopra-fs22-group-29/brandi-server#48

- [x] sopra-fs22-group-29/brandi-server#49
