### ISSUE TITLE
As a registered user, I want to be able to send a code to a new game to my friends such that  we can play together.

### ISSUE THREAD

**Issue by EriCreator** [sopra-fs22-group-29/brandi-server#4]
**Acceptance Criteria:**

- Upon Login the user can click a button to generate a new code to a new game session and share this with his friends

- [x] sopra-fs22-group-29/brandi-client#37
- [x] sopra-fs22-group-29/brandi-client#5
- [x] sopra-fs22-group-29/brandi-server#27
