### ISSUE TITLE
As a registered user entering a new game session, I want to see the initial game board and  the distributed cards such that I know which my color is and who my partner is.

### ISSUE THREAD

**Issue by EriCreator** [sopra-fs22-group-29/brandi-server#6]
**Acceptance Criteria:**

- Upon successful entering a new game session, the user sees the game board with all the marbles in their base
- The user can see the first 6 cards to play
- The user can see which of the other player is its partner and which are its opponent

- [x] sopra-fs22-group-29/brandi-client#9
- [x] sopra-fs22-group-29/brandi-client#10
- [x] sopra-fs22-group-29/brandi-client#29
- [x] sopra-fs22-group-29/brandi-client#30
- [x] sopra-fs22-group-29/brandi-client#31
- [x] sopra-fs22-group-29/brandi-server#53 
- [x] sopra-fs22-group-29/brandi-server#54 
- [x] sopra-fs22-group-29/brandi-server#55
