### ISSUE TITLE
As a user, I want to be able to draw a card from my hand in order to play it.

### ISSUE THREAD

**Issue by EriCreator** [sopra-fs22-group-29/brandi-server#8]
**Acceptance Criteria:**

- Users that are actively participating in a game want to see the cards they have on the screen
- Users in a game want to pick one of their cards and play it

- [x] sopra-fs22-group-29/brandi-client#12
- [x] sopra-fs22-group-29/brandi-server#38
- [x] sopra-fs22-group-29/brandi-client#34
