### ISSUE TITLE
As a user in a game, I want to get information about my state, such that I know when my turn is.

### ISSUE THREAD

**Issue by ElenaGrafUZH** [sopra-fs22-group-29/brandi-server#93]
**Acceptance Criteria**

- If it's the players turn, the player sees an information "Your turn!"
- If the player needs to wait until it is the players turn again, the players sees an information "Waiting..."

**Tasks**
- [x] sopra-fs22-group-29/brandi-client#66
- [x] sopra-fs22-group-29/brandi-client#67
- [x] sopra-fs22-group-29/brandi-server#94
